Suppress compiler warnings
sosemanuk.c: In function ‘xorbuf’:
sosemanuk.c:1022:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  if (!(((unsigned)in1 | (unsigned)in2 | (unsigned)out) & 0x03)) {
         ^
sosemanuk.c:1022:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  if (!(((unsigned)in1 | (unsigned)in2 | (unsigned)out) & 0x03)) {
                         ^
sosemanuk.c:1022:41: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  if (!(((unsigned)in1 | (unsigned)in2 | (unsigned)out) & 0x03)) {

Suppress compiler warnings

crypto.cc: In function ‘package bf_salt(Var, Byte, void*, Objid)’:
crypto.cc:237:12: warning: unused variable ‘input_length’ [-Wunused-variable]
     size_t input_length = memo_strlen(input);

Suppress compiler warnings

fileio.cc: In function ‘package bf_file_read(Var, Byte, void*, Objid)’:
fileio.cc:772:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   read_length = (record_length > sizeof(buffer)) ? sizeof(buffer) : record_length;

Suppress compiler warnings

json.cc: In function ‘yajl_gen_status generate(yajl_gen, Var, void*)’:
json.cc:438:12: warning: enumeration value ‘_TYPE_STR’ not handled in switch [-Wswitch]
     switch (v.type) {
            ^
json.cc:438:12: warning: enumeration value ‘_TYPE_LIST’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘TYPE_CLEAR’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘TYPE_NONE’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘TYPE_CATCH’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘TYPE_FINALLY’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘_TYPE_FLOAT’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘_TYPE_MAP’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘_TYPE_ITER’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘_TYPE_ANON’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘TYPE_ITER’ not handled in switch [-Wswitch]
json.cc:438:12: warning: enumeration value ‘TYPE_ANON’ not handled in switch [-Wswitch]

Suppress compiler warnings

map.cc:550:1: warning: ‘rbnode* rbtlast(rbtrav*, rbtree*)’ defined but not used [-Wunused-function]
 rbtlast(rbtrav *trav, rbtree *tree)
 ^
map.cc:568:1: warning: ‘rbnode* rbtprev(rbtrav*)’ defined but not used [-Wunused-function]
 rbtprev(rbtrav *trav)
 ^

Suppress compiler warnings

name_lookup.cc: In function ‘void lookup(int, int)’:
name_lookup.cc:174:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   != req.u.length)
            ^
name_lookup.cc: In function ‘void intermediary(int, int)’:
name_lookup.cc:245:66: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      if (robust_read(from_server, buffer, req.u.length) != req.u.length)
                                                                  ^

Suppress compiler warnings

In file included from network.cc:23:0:
net_multi.cc: In function ‘void accept_new_connection(nlistener*)’:
net_multi.cc:412:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < proto.pocket_size; i++)
                        ^
net_multi.cc: In function ‘void network_set_client_echo(network_handle, int)’:
net_multi.cc:646:24: warning: narrowing conversion of ‘255’ from ‘int’ to ‘char’ inside { } is ill-formed in C++11 [-Wnarrowing]
  {TN_IAC, 0, TN_ECHO, 0};

Suppress compiler warnings

streams.cc: In function ‘void grow(Stream*, int, int)’:
streams.cc:65:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (newlen > stream_alloc_maximum) {
               ^
streams.cc:66:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      if (s->current + need < stream_alloc_maximum)

Type change

In relation to commit 119c793

Suppress compiler warnings

timers.cc: In function ‘void reenable_timers()’:
timers.cc:289:20: warning: ‘int sigsetmask(int)’ is deprecated (declared at /usr/include/signal.h:200) [-Wdeprecated-declarations]
     int old_mask = sigsetmask(-1); /* block everything, get old mask */
                    ^
timers.cc:289:33: warning: ‘int sigsetmask(int)’ is deprecated (declared at /usr/include/signal.h:200) [-Wdeprecated-declarations]
     int old_mask = sigsetmask(-1); /* block everything, get old mask */
                                 ^
timers.cc:292:5: warning: ‘int sigsetmask(int)’ is deprecated (declared at /usr/include/signal.h:200) [-Wdeprecated-declarations]
     sigsetmask(old_mask); /* reset the signal mask */
     ^
timers.cc:292:24: warning: ‘int sigsetmask(int)’ is deprecated (declared at /usr/include/signal.h:200) [-Wdeprecated-declarations]
     sigsetmask(old_mask); /* reset the signal mask */

Suppress compiler warnings

base64.cc: In function ‘package bf_encode_base64(Var, Byte, void*, Objid)’:
base64.cc:74:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((len / 3) * 4 > stream_alloc_maximum) {
                         ^
base64.cc: In function ‘package bf_decode_base64(Var, Byte, void*, Objid)’:
base64.cc:174:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < len; i++) {
                     ^
base64.cc:212:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < len + len % 4; i++) {
                                 ^
base64.cc:213:10: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (i < len) {

Suppress compiler warnings

utils.cc:530:24: warning: array subscript has type ‘char’ [-Wchar-subscripts]
  int c = temp[source[i]];

Suppress compiler warnings

garbage.cc: At global scope:
garbage.cc:106:1: warning: ‘void gc_debug(const char*)’ defined but not used [-Wunused-function]
 gc_debug(const char *name)

Suppress compiler warnings

db_properties.cc: In function ‘int db_add_propdef(Var, const char*, Var, Objid, unsigned int)’:
db_properties.cc:193:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < o->propdefs.max_length; i++)
                              ^
db_properties.cc: In function ‘int db_delete_propdef(Var, const char*)’:
db_properties.cc:319:56: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      if (max > 8 && props->cur_length <= ((max * 3) / 8)) {
                                                        ^
db_properties.cc: In function ‘int dbpriv_check_properties_for_chparent(Var, Var, Var)’:
db_properties.cc:755:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (x = 0; x < props->cur_length; x++) {
                         ^
db_properties.cc:787:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      for (x = 0; x < props->cur_length; x++) {
                             ^
In file included from db_properties.cc:22:0:
db_properties.cc: In function ‘void dbpriv_fix_properties_after_chparent(Var, Var, Var, Var)’:
db_properties.cc:903:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     assert(old_count == me->nval);
                             ^
db_properties.cc: At global scope:
db_properties.cc:392:1: warning: ‘int add_to_list(void*, Objid)’ defined but not used [-Wunused-function]
 add_to_list(void *data, Objid c)

Suppress compiler warnings

db_file.cc: In function ‘int v4_read_object()’:
db_file.cc:276:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < o->propdefs.cur_length; i++) {
                              ^
db_file.cc: In function ‘int ng_read_object(int)’:
db_file.cc:358:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < o->propdefs.cur_length; i++) {
                              ^
db_file.cc: In function ‘void v4_write_object(Objid)’:
db_file.cc:417:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < o->propdefs.cur_length; i++)
                                 ^
db_file.cc: In function ‘void ng_write_object(Objid)’:
db_file.cc:461:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < o->propdefs.cur_length; i++)
                                 ^
db_file.cc: At global scope:
db_file.cc:381:1: warning: ‘void v4_write_object(Objid)’ defined but not used [-Wunused-function]
 v4_write_object(Objid oid)

Change type

In relation to commit f8b4c16

Suppress compiler warnings

db_verbs.cc: In function ‘db_verb_handle db_find_command_verb(Objid, const char*, db_arg_spec, unsigned int, db_arg_spec)’:
db_verbs.cc:325:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   && (v->prep == PREP_ANY || v->prep == prep)

Suppress compiler warnings

db_verbs.cc: In function ‘void dbpriv_build_prep_table()’:
utils.h:32:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define Arraysize(x) (sizeof(x) / sizeof(*x))
                                             ^
db_verbs.cc:68:16: note: in expansion of macro ‘Arraysize’
 #define NPREPS Arraysize(prep_list)
                ^
db_verbs.cc:89:21: note: in expansion of macro ‘NPREPS’
     for (i = 0; i < NPREPS; i++) {
                     ^
db_verbs.cc: In function ‘db_prep_spec db_find_prep(int, char**, int*, int*)’:
utils.h:32:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define Arraysize(x) (sizeof(x) / sizeof(*x))
                                             ^
db_verbs.cc:68:16: note: in expansion of macro ‘Arraysize’
 #define NPREPS Arraysize(prep_list)
                ^
db_verbs.cc:127:18: note: in expansion of macro ‘NPREPS’
  for (j = 0; j < NPREPS; j++) {
                  ^
db_verbs.cc: In function ‘db_prep_spec db_match_prep(const char*)’:
utils.h:32:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define Arraysize(x) (sizeof(x) / sizeof(*x))
                                             ^
db_verbs.cc:68:16: note: in expansion of macro ‘Arraysize’
 #define NPREPS Arraysize(prep_list)
                ^
db_verbs.cc:167:33: note: in expansion of macro ‘NPREPS’
  if (!isdigit(first) || prep >= NPREPS)
                                 ^

Suppress compiler warnings

decompile.cc: In function ‘Stmt* program_to_tree(Program*, int, int, int)’:
decompile.cc:913:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     else if (pc < bc.size)
                      ^
decompile.cc:919:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     hot_position = (pc == bc.size - 1 ? DONE : TOP);
                                     ^
decompile.cc:922:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < program->fork_vectors_size; i++)

Suppress compiler warnings

disassemble.cc: In function ‘void disassemble(Program*, Printer, void*)’:
disassemble.cc:219:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = -1; i < 0 || i < prog->fork_vectors_size; i++) {
                                     ^
disassemble.cc:327:65: warning: operation on ‘tmp’ may be undefined [-Wsequence-point]
       stream_printf(insn, " %s %s %d", NAMES(a1), NAMES(a2), a3);

Suppress compiler warnings

db_objects.cc: In function ‘void extend(unsigned int)’:
db_objects.cc:91:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size = 128; size <= new_objects; size *= 2)
                              ^
db_objects.cc:108:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size = 4096; size <= new_objects; size *= 2)
                               ^
db_objects.cc:115:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (size > array_size) {
                ^
db_objects.cc: In function ‘void db_destroy_object(Objid)’:
db_objects.cc:252:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < o->propdefs.cur_length; i++) {
                                 ^
db_objects.cc: In function ‘void db_destroy_anonymous_object(void*)’:
db_objects.cc:377:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < o->propdefs.cur_length; i++)
                                 ^
db_objects.cc:381:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < o->nval; i++)
                        ^
db_objects.cc: In function ‘int db_object_bytes(Var)’:
db_objects.cc:566:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < o->propdefs.cur_length; i++)

Suppress compiler warnings

execute.cc: In function ‘void print_error_backtrace(const char*, void (*)(const char*))’:
execute.cc:130:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (t != top_activ_stack)
           ^
execute.cc:151:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (t == top_activ_stack)
           ^
execute.cc: In function ‘int unwind_stack(Finally_Reason, Var, outcome*)’:
execute.cc:231:8: warning: variable ‘player’ set but not used [-Wunused-but-set-variable]
  Objid player;
        ^
execute.cc: In function ‘int push_activation()’:
execute.cc:552:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (top_activ_stack < max_stack_size - 1) {
                                            ^
execute.cc: In function ‘outcome run(char, error, Var*)’:
execute.cc:958:14: warning: unused variable ‘e’ [-Wunused-variable]
   enum error e = E_NONE;
              ^
execute.cc:1916:15: warning: unused variable ‘e’ [-Wunused-variable]
    enum error e;
               ^
execute.cc:2432:60: warning: suggest parentheses around ‘-’ inside ‘<<’ [-Wparentheses]
 #define MASK(n) (~(Num)(~(UNum)0 << sizeof(Num) * CHAR_BIT - (n)))
                                                            ^
execute.cc:2433:45: note: in expansion of macro ‘MASK’
 #define SHIFTR(n, m) ((Num)((UNum)n >> m) & MASK(m))
                                             ^
execute.cc:2439:17: note: in expansion of macro ‘SHIFTR’
     ans.v.num = SHIFTR(lhs.v.num, rhs.v.num);
                 ^
execute.cc: In function ‘int read_rt_env(const char***, Var**, int*)’:
execute.cc:3355:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < *old_size; i++) {
                      ^
execute.cc: In function ‘Var* reorder_rt_env(Var*, const char**, int, Program*)’:
execute.cc:3390:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < old_size; i++) {
                     ^
execute.cc:3396:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < old_size; i++)
                     ^
execute.cc: In function ‘int read_activ(activation*, int)’:
execute.cc:3492:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < stack_in_use; i++)

Type change

In relation to commit b99d801

Type change

In relation to commit b99d801

Fix compiler warnings

db_file.cc: In function ‘void ng_write_object(Objid)’:
db_file.cc:461:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < o->propdefs.cur_length; i++)

Suppress compiler warnings

db_objects.cc: In function ‘void dbpriv_after_load()’:
db_objects.cc:138:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = num_objects; i < max_objects; i++) {
                               ^

Fix mistake

Too much disabled code

Suppress compiler warnings

execute.cc: In function ‘int read_rt_env(const char***, Var**, int*)’:
execute.cc:3345:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < *old_size; i++) {

Fix linker error

/apps/moo/qa/stunt/execute.cc:3462: undefined reference to `read_rt_env(char const***, Var**, unsigned int*)'
tasks.o: In function `read_task_queue()':
/apps/moo/qa/stunt/tasks.cc:1986: undefined reference to `read_rt_env(char const***, Var**, unsigned int*)'
collect2: error: ld returned 1 exit status
make: *** [moo] Error 1